services:

  nginx:
    container_name: ${NGINX_NAME}
    build:
      context: .
      args:
        TAG: ${NGINX_TAG}
    restart: always
    networks:
      - default
    ports:
      - ${NGINX_HTTP_PORT}:8080
      - ${NGINX_HTTPS_PORT}:8443
    environment:
      APP_ENV: ${APP_ENV}
      USER_ID: ${USER_ID}
      GROUP_ID: ${GROUP_ID}
